
#+TITLE: manga printer
#+OPTIONS: num:nil

* What is this?
This is a program that sorts pages from multiple chapters into a correct printing order so that the sheets can be bound easily. \\

Currently only supported on Linux, although I will test with macOS once I have a finished program. \\

Made for fun and to learn Perl. \\
* Installation
Simply clone the repo and move the "insert title of main perl script here" to the directory of the series, i.e. the folder that has all the chapter folders in it, then run the program by typing the following in the terminal:
#+begin_src shell
  $ ./"title of script".pl
#+end_src
* Dependencies
- Perl 5
- Linux (although macOS should work... if you're on windows good luck lmao)
  * using a linux vm to sort the pages would probably work...

* Project Plans
- sort pages in each folder (bare minimum for a release)
- create pdfs of the sorted pages (using imagemagick or ffmpeg???)
- option to concatenate pdfs into one large one
- multiple sorting options - left to right, right to left, etc.
- ability to run program from the repo folder, stdout the desired directory and run from there
  
 
